const works = [
    // LANDSCAPE (16:9 가로형)
    {
        id: 52,
        title: "이제 디바이스로 이거까지 발라보세요｜쿼드쎄라 실험일기 #1",
        client: "쿼드쎄라",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/-hFHV9wCdcA/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/-hFHV9wCdcA",
        description: "교차초음파 디바이스 티탄을 사용한 엉뚱한 실험! 화장품 대신 연고를 바르면 어떨까요?",
    },
    {
        id: 53,
        title: "쿼드쎄라 4주 챌린지 VLOG #1",
        client: "쿼드쎄라",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/hykU5dDZCow/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/hykU5dDZCow",
        description: "4주간 쿼드쎄라와 함께하는 건강한 습관 만들기 브이로그 코너입니다.",
    },
    {
        id: 54,
        title: "국힙주간소식: 빅나티, 스윙스, 키드밀리 외",
        client: "JJK",
        category: "DOCUMENTARY",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/kGUR2tYD8xk/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/kGUR2tYD8xk",
        description: "매주 국내 힙합계의 다양한 소식을 전해드리는 주간 뉴스 형식의 콘텐츠입니다.",
    },
    {
        id: 55,
        title: "떴다떴다현 EP.3: 인성파탄 음치 가수 연기?!",
        client: "김다현TV",
        category: "DOCUMENTARY",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/IFoSulSNC70/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/IFoSulSNC70",
        description: "다현이가 보컬 레슨에서 음치인 척 연기하며 벌어지는 코미디 에피소드입니다.",
    },
    {
        id: 56,
        title: "노화와 각진 얼굴을 위한 괄사 마사지 팁",
        client: "뷰티팟TV",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/AGYSlO00Dp8/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/AGYSlO00Dp8",
        description: "25년 경력 전문가가 전하는 괄사 효과 극대화 방법 설명 영상입니다.",
    },
    {
        id: 57,
        title: "댓글 읽다 조선의 국모 된 사연?!",
        client: "김다현TV",
        category: "DOCUMENTARY",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/7cD23OslJdo/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/7cD23OslJdo",
        description: "구독자 댓글을 읽으며 소통하는 다현이의 솔직하고 유쾌한 시간입니다.",
    },
    {
        id: 58,
        title: "트롯요정 김다현 신곡 자켓 촬영 비하인드",
        client: "김다현TV",
        category: "DOCUMENTARY",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/qjI234b6fiw/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/qjI234b6fiw",
        description: "신곡 '꿈길'과 '박수 쳐' 자켓 촬영 현장의 생생한 뒷이야기를 담았습니다.",
    },
    {
        id: 59,
        title: "온누리 상품권 120원 편",
        client: "위원 (Wewon)",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://i.vimeocdn.com/video/2126205168-1f52af03fc1a6b86b91ebd12fdf8578b340e49f92edf5a18489e685ca411afbb-d?f=webp&region=us",
        videoUrl: "https://player.vimeo.com/video/1168006604",
        description: "온누리 상품권 120원과 관련된 에피소드 영상입니다.",
    },
    {
        id: 60,
        title: "온누리 상품권 알바비 편",
        client: "위원 (Wewon)",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://i.vimeocdn.com/video/2126203783-fea41d760f2fd16f70009d98dea9528cbdc68b6b24166379d57622fc57222eb0-d?f=webp&region=us",
        videoUrl: "https://player.vimeo.com/video/1168006627",
        description: "온누리 상품권으로 알바비를 받는 독특한 상황을 연출한 영상입니다.",
    },
    {
        id: 46,
        title: "📢숨겨진 최고의 인증 중고차 보물을 찾아라! 한성트레저 EP.1💎",
        client: "한성자동차",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/ClX7DnBhzL4/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/ClX7DnBhzL4",
        description:
            "최고의 인증 중고차를 찾는 한성트레저 첫 번째 이야기 영상입니다.",
    },
    {
        id: 47,
        title: "[월간한성📅] 11월 한성자동차 전시장 혜택 및 프로모션 모아보기!",
        client: "한성자동차",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/WzI1WeaABbk/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/WzI1WeaABbk",
        description:
            "11월 한성자동차 전시장 혜택 및 프로모션을 소개하는 영상입니다.",
    },
    {
        id: 44,
        title: "Mercedes-AMG G 63 오너의 남다른 일상 ㅣ 한성 SEE. Vol.2",
        client: "한성자동차",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/P0brARRRS_c/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/P0brARRRS_c",
        description:
            "Mercedes-AMG G 63 오너의 남다른 일상을 담은 한성 SEE. Vol.2 영상입니다.",
    },
    {
        id: 45,
        title:
            "📢숨겨진 최고의 인증 중고차 보물을 찾아라! 한성트레저 두번째 이야기💎",
        client: "한성자동차",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/ZeiWlxHSKWY/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/ZeiWlxHSKWY",
        description:
            "최고의 인증 중고차를 찾는 한성트레저 두 번째 이야기 영상입니다.",
    },
    {
        id: 43,
        title:
            "[안전로드 퀴즈쇼] 드디어 등장한 현대모비스 아이돌?✨ 우리 회사 자랑 좀 들어보세요😎 | 현대모비스 본사",
        client: "현대모비스",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/PofMcsINkHc/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/PofMcsINkHc",
        description: "현대모비스 본사에서 진행된 안전로드 퀴즈쇼 영상입니다.",
    },
    {
        id: 22,
        title: "Mirabelle Korea 2025 Brand Film",
        client: "Mirabelle Korea",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/tjn6_Tp6bGo/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/tjn6_Tp6bGo",
        description: "Mirabelle Korea 2025 브랜드 필름입니다.",
    },
    {
        id: 51,
        title: "딥플로우, 지금 한국 힙합에서 제일 허슬하는 래퍼 | INTERVIEW",
        client: "JJK",
        category: "DOCUMENTARY",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/TJlDHFNOnpM/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/TJlDHFNOnpM",
        description:
            "딥플로우 - 지금 한국 힙합에서 제일 허슬하는 래퍼, 인터뷰 영상입니다.",
    },
    {
        id: 49,
        title: "지코, 한국 힙합과 K-POP을 넘나들며 | INTERVIEW",
        client: "JJK",
        category: "DOCUMENTARY",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/BggUcEa3Ess/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/BggUcEa3Ess",
        description: "지코 - 한국 힙합과 K-POP을 넘나들며, 인터뷰 영상입니다.",
    },
    {
        id: 50,
        title: "팔로알토의 음악과 태도와 밈까지 다 파헤치다 | INTERVIEW",
        client: "JJK",
        category: "DOCUMENTARY",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/MDsM0hz38H0/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/MDsM0hz38H0",
        description: "팔로알토의 음악과 태도, 밈까지 파헤치는 인터뷰 영상입니다.",
    },
    {
        id: 48,
        title: "🌙 MELLBEU ASMR |촉촉한 피부를 위한 스킨케어 심포니",
        client: "멜비유(mellbeu)",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/CGRANENdmn0/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/CGRANENdmn0",
        description: "촉촉한 피부를 위한 멜비유 스킨케어 심포니 ASMR 영상입니다.",
    },
    {
        id: 39,
        title: "지하니_수분라인-1",
        client: "Vimeo",
        category: "BRAND",
        orientation: "landscape",
        thumbnail:
            "https://i.vimeocdn.com/video/2125713132-e9aaaf337903130fc6b3ca6edc27dfb70ee5114aacd249086143e6b93819127b-d_1280?region=us",
        videoUrl: "https://player.vimeo.com/video/1167646145",
        description: "지하니 피부 수분라인 소개 영상입니다.",
    },
    {
        id: 40,
        title: "온누리상품권이별-1",
        client: "Vimeo",
        category: "BRAND",
        orientation: "landscape",
        thumbnail:
            "https://i.vimeocdn.com/video/2125713291-2265b8cfd78d386b9d6236b5520ba24709e88bf642c276fa490cbe169ef82dbc-d_1280?region=us",
        videoUrl: "https://player.vimeo.com/video/1167646253",
        description: "온누리상품권 이별 단편 영상입니다.",
    },
    {
        id: 41,
        title: "온누리상품권500원이_없어서-1",
        client: "Vimeo",
        category: "BRAND",
        orientation: "landscape",
        thumbnail:
            "https://i.vimeocdn.com/video/2125713326-a54dabd4eda07d326a4e72c1c290f9258f4580b5bedd933953fd0b0d0bda2038-d_1280?region=us",
        videoUrl: "https://player.vimeo.com/video/1167646281",
        description: "온누리상품권 500원이 없어서 생긴 에피소드 영상입니다.",
    },
    {
        id: 42,
        title:
            "김다현 1390만 유튜버 대선배 햄지님과 먹방 했습니다😋🍴 #김다현 #김다현tv",
        client: "김다현",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/OaGTS4ybsYQ/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/OaGTS4ybsYQ",
        description: "1390만 유튜버 햄지님과의 먹방 콜라보레이션 영상입니다.",
    },
    {
        id: 36,
        title: "대전 최대 규모 스포츠센터, CNU 스포렉스 센터",
        client: "충남대학교",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/s4cqLJhCgE8/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/s4cqLJhCgE8",
        description:
            "대전 최대 규모를 자랑하는 CNU 스포렉스 센터의 시설과 활기를 소개하는 영상입니다.",
    },
    {
        id: 37,
        title: "피부 RETURN 시리즈 콜라젠 리프팅 입점",
        client: "YouTube",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/QbwHp3gcZDE/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/QbwHp3gcZDE",
        description:
            "콜라젠 리프팅 입점 소식과 제품의 매력을 담은 브랜드 영상입니다.",
    },
    {
        id: 27,
        title: "영하의 날씨에 버려진 누더기 실버푸들 미용했어요🩷",
        client: "YouTube",
        category: "OTHERS",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/nyiKexi9NSw/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/nyiKexi9NSw",
        description: "추운 날씨에 구조된 실버푸들의 미용 과정 영상입니다.",
    },
    {
        id: 28,
        title: "25년 경력 뷰티팟 TV 송원장의 브랜드 '퀸즈본가'",
        client: "퀸즈본가",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/atuODTDp0Qk/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/atuODTDp0Qk",
        description: "뷰티 브랜드 퀸즈본가 소개 영상입니다.",
    },
    {
        id: 29,
        title: "소향 - 나 언젠가 떠날거야 (디즈니 모아나 커버)",
        client: "진제이",
        category: "MUSIC_VIDEO",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/MEOo7CNdcXs/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/MEOo7CNdcXs",
        description: "디즈니 모아나 OST '나 언젠가 떠날거야' 커버 영상입니다.",
    },
    {
        id: 30,
        title: "WOO(성현우) - 없었던 것처럼 LIVE CLIP",
        client: "WOO(성현우)",
        category: "MUSIC_VIDEO",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/42BldXKgIao/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/42BldXKgIao",
        description: "WOO(성현우)의 '없었던 것처럼' 라이브 클립입니다.",
    },
    {
        id: 31,
        title: "WOO(성현우) - DiNA LIVE CLIP",
        client: "WOO(성현우)",
        category: "MUSIC_VIDEO",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/-XrWUXBvyMY/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/-XrWUXBvyMY",
        description: "WOO(성현우)의 'DiNA' (원곡.Yuuri/優里) 라이브 클립입니다.",
    },
    {
        id: 32,
        title: "덥덥이(dubdubee) - Again and Again(Official MV)",
        client: "덥덥이",
        category: "MUSIC_VIDEO",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/XHGNBDjRgdQ/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/XHGNBDjRgdQ",
        description: "덥덥이의 'Again and Again' 공식 뮤직비디오입니다.",
    },
    {
        id: 33,
        title: "랩레슨 싸이퍼 촬영 비하인드",
        client: "326-2KIDS",
        category: "DOCUMENTARY",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/hqh2-3iBWM4/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/hqh2-3iBWM4",
        description: "랩레슨 싸이퍼 촬영 비하인드 영상입니다.",
    },
    {
        id: 34,
        title: "흉터치료 새살침, 치료 방법과 접근법",
        client: "흉지사",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/GCJ6Qkosgaw/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/GCJ6Qkosgaw",
        description: "피부 유형에 따른 흉터치료 새살침의 접근법을 소개합니다.",
    },
    {
        id: 20,
        title: "집 [대전CKL 2차 유튜브 콘테스트 공모작]",
        client: "YouTube",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/3umEWnQN_oM/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/3umEWnQN_oM",
        description: "대전CKL 2차 유튜브 콘테스트 공모작 '집' 영상입니다.",
    },
    {
        id: 21,
        title: "인간극장 : 존재의 이유",
        client: "KOHI",
        category: "DOCUMENTARY",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/gv_7288qSng/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/gv_7288qSng",
        description: "2023년 KOHI 사회복무요원 SNS 영상 공모전 대상 수상작입니다.",
    },
    {
        id: 23,
        title: "피부 고민 하던 지하니, 결국 사버린 찐템은? 🛍",
        client: "YouTube",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/X8bjIyiJeYI/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/X8bjIyiJeYI",
        description: "피부 고민 타파를 위한 찐템 소개 영상입니다.",
    },
    {
        id: 24,
        title: "너는 누구이고 싶어? BE YOU, MELLBEU",
        client: "MELLBEU",
        category: "BRAND",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/yEhwdmJ5xTg/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/yEhwdmJ5xTg",
        description: "MELLBEU 브랜드 영상 'BE YOU' 입니다.",
    },
    {
        id: 25,
        title: "수은등-김연자 l COVER BY 김다현",
        client: "김다현",
        category: "MUSIC_VIDEO",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/uCIRKVpoXb4/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/uCIRKVpoXb4",
        description: "김다현의 '수은등' 커버 영상입니다.",
    },
    {
        id: 26,
        title: "트롯요정 김다현, 과연 몇 명이나 알아볼까? 🤔",
        client: "김다현",
        category: "DOCUMENTARY",
        orientation: "landscape",
        thumbnail: "https://img.youtube.com/vi/xvwhyCuUO-Q/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/xvwhyCuUO-Q",
        description: "관악중부시장에서 진행된 떴다떴다현 에피소드 1입니다.",
    },

    // PORTRAIT (9:16 세로형) - 신규 영상을 최상단으로 이동
    {
        id: 61,
        title: "한의사가 맥 짚을 때 잘생기면 위험한 이유",
        client: "@rodamcora",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "https://i.ytimg.com/vi/4DMQj-Fs9sU/oar2.jpg?sqp=-oaymwEoCJUDENAFSFqQAgHyq4qpAxcIARUAAIhC2AEB4gEKCBgQAhgGOAFAAQ==&rs=AOn4CLChWspNrgeZpmdnqBIRmlhrahoiaQ&usqp=CCk",
        videoUrl: "https://www.youtube.com/embed/4DMQj-Fs9sU",
        description: "흉지사 한의원 쇼츠! 부정맥과 관련된 재미있는 의학 정보입니다.",
    },
    {
        id: 62,
        title: "한의사 출근룩 얼마면 될까?",
        client: "@rodamcora",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "https://i.ytimg.com/vi/osv4ys0DvUs/oardefault.jpg?sqp=-oaymwEoCJUDENAFSFqQAgHyq4qpAxcIARUAAIhC2AEB4gEKCBgQAhgGOAFAAQ==&rs=AOn4CLDqMgyzGhqRrnHqAZjU8QncNUeg4g&usqp=CCk",
        videoUrl: "https://www.youtube.com/embed/osv4ys0DvUs",
        description: "한의사의 출근룩을 알아보는 가벼운 브이로그 쇼츠입니다.",
    },
    {
        id: 63,
        title: "민생지원금? 오늘 바로 오시죠!",
        client: "@rodamcora",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "https://i.ytimg.com/vi/pqF8Q-lrl1Y/oar2.jpg?sqp=-oaymwEoCJUDENAFSFqQAgHyq4qpAxcIARUAAIhC2AEB4gEKCBgQAhgGOAFAAQ==&rs=AOn4CLB4-PzHU30EkgWj_BWH6190_iJMIw&usqp=CCk",
        videoUrl: "https://www.youtube.com/embed/pqF8Q-lrl1Y",
        description: "민생소비쿠폰 활용 꿀팁을 전하는 흉지사 한의원 정보 쇼츠입니다.",
    },
    {
        id: 64,
        title: "에어리어 카카오 쇼핑라이브 홍보",
        client: "airear_kr",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/574226361_1198442111652989_3848702608350345412_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=111&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=XT1EVSVcoJgQ7kNvwFGBf7g&_nc_oc=Adn6LH-xQoMxXNkyBQnrDihXa2QPXexe5ZhzjzavdS21tPwC8kCAjjSX4NP937nYWeI&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Nxj74c2WzVCWsRUyA4gsng&oh=00_AfvaMm4Frqb7YHCYlPI5UHI6ByyaQ5r-cX9CXjdvlYcS2Q&oe=69A48C32",
        videoUrl: "https://www.instagram.com/reel/DR_3cSFk2cH/embed",
        description: "카카오 쇼핑라이브 특가 혜택을 알리는 감각적인 광고 릴스입니다.",
    },
    {
        id: 65,
        title: "오브룸 미니고데기 리뷰",
        client: "ovroom.korea",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/630096563_17922675036239210_3037750481159552720_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=ndJ_tT0OyFUQ7kNvwFLWbkb&_nc_oc=AdlkDrSM4sBuBuyCzjOB0GflQ61QyCuF37DrksDAB1fFtLU6v3p7OFViqzgzIFGc92E&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=lTR25AM-fSwNCWLNAkxiPA&oh=00_Afs-Rm5EQ-Hveg8cg71fx_1ME29vp9FVVewdYiaxqco6oQ&oe=69A46A55",
        videoUrl: "https://www.instagram.com/reel/DUhSq6Bj2PR/embed",
        description: "초경량 휴대용 미니 고데기의 성능과 휴대성을 보여주는 리뷰 영상입니다.",
    },
    {
        id: 66,
        title: "한번만 빌려줘! 빌런 친구 대처법",
        client: "ovroom.korea",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/618636071_17920320291239210_6666283435214916666_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=109&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=XeRb8QJjmjQQ7kNvwHOvysp&_nc_oc=AdnNBrH2a9KRjPsiz-1MQEoVoMsnAdZ1fA-6CGi3gDOdWDgtyP585fKS2P0TXB3ad9w&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=QwP93eSCTiLRh67EtFB2rA&oh=00_Afv-4Gnr-0HSh4azFsvW9wGnvxgtoz_O8rt0dE61lRVpzA&oe=69A48DC1",
        videoUrl: "https://www.instagram.com/reel/DTui2Wgjxul/embed",
        description: "공감 100%! 한번만 빌려달라는 친구와의 유쾌한 일상을 담았습니다.",
    },
    {
        id: 67,
        title: "AJAZZ 기계식 키보드 국내 정식 발매",
        client: "ajazz.official",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/629784655_759859447180757_5778616884092245894_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=p5P3C90Dz_EQ7kNvwE1tlxS&_nc_oc=AdkmqnBrJNbQPNGonGQz8jVyGyxyapCaC2nVOXbUfSgWUeJM4wjWu_s1VU-9MpfaRkg&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Vvh1psKCpWrya8BBfiPaEg&oh=00_Afv3tm6PbRgWQYzQI9RsmZjy5bQFKHKQL61tNez03wmOSQ&oe=69A49271",
        videoUrl: "https://www.instagram.com/reel/DUsB_WhEmfo/embed",
        description: "글로벌 키보드 브랜드 AJAZZ의 국내 런칭 소식을 담은 숏폼 광고입니다.",
    },
    {
        id: 68,
        title: "얼굴이 까매진 진짜 이유?",
        client: "ecowon",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/560357661_2779867552208241_6160852973236872195_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=110&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=9JmE_Wg-oUgQ7kNvwFlFRTV&_nc_oc=AdkHujNYkoYzA9PeEjzNOlKSdyNH8SPEP8ekBqIf76RJtmrsAL_TZ4Ch_D2CVZthIkA&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=BW99D1yASkSjL45MHdhtVg&oh=00_AftVyPmmw-rUEgRTyF14Ait-JsAVVbBKCimUe5Uz3hUsfQ&oe=69A48EBC",
        videoUrl: "https://www.instagram.com/reel/DPjDPPHEprP/embed",
        description: "BBQ 그릴 열기 때문일까요? 코믹한 상황 설정이 돋보이는 릴스입니다.",
    },
    {
        id: 69,
        title: "젤리 먹방: 아이스 젤리 편",
        client: "@1ndian2wins",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/641255091_1205922675047976_3308620692795010790_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=106&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=gmBnde9fDmYQ7kNvwEoE8lm&_nc_oc=AdnIM6Pj_8VjeQNLWzsJ2JidyM82zm1r--8ieriigpDt4M_6OvxpoXIXfoSNNuc8YL8&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=GF8q4zW5pOUiA40pRrdJwQ&oh=00_AfvTbUPzXpzgqyJegS90fbg3Zs5lkouIMLo6CpgmEJE0TQ&oe=69A48E5F",
        videoUrl: "https://www.threads.net/@1ndian2wins/post/DVJChTZkpO4/embed",
        description: "구독자 요청으로 진행된 시원한 젤리 먹방 사운드와 영상입니다.",
    },
    {
        id: 70,
        title: "외국인들의 한국 설날 야식 먹방",
        client: "@1ndian2wins",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/639717142_33891111740535763_3712756212631654887_n.jpg?stp=cmp1_dst-jpg_e35_s640x640_tt6&_nc_cat=111&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=UsoAUChZ77YQ7kNvwE_2x8I&_nc_oc=AdmUc-SnTnfS-OkXg-6H8g_xQlwQdEhUUElUOXm680VIO1CchjQ3YoFybvY7oIGOic4&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=GZye-uZ_h_zWAO3EpbrFCg&oh=00_Afv5bs8m7kxtRdD4aDWMbpfDVaIbcIvxYCOWzjXIgATTOA&oe=69A47D56",
        videoUrl: "https://www.threads.net/@1ndian2wins/post/DU-TO8VEqKd/embed",
        description: "명절 음식으로 야식을 즐기는 외국인 친구들의 리액션을 담았습니다.",
    },
    // PORTRAIT (9:16 세로형) - 신규 영상을 최상단으로 이동
    {
        id: 19,
        title: "Mirabelle Korea: K-Solutions",
        client: "Mirabelle Korea",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "images/works/thumb_hq_19.jpg",
        videoUrl: "https://www.instagram.com/reel/DMdGy21PiTy/embed",
        description:
            "인도를 위한 K-솔루션. 다양한 기후와 피부 타입에 맞춘 현지화된 K-뷰티 스킨케어를 소개합니다.",
    },
    {
        id: 14,
        title: "TikTok: Creative Edit",
        client: "@1ndian2wins",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "images/works/thumb_hq_14.jpg",
        videoUrl: "https://www.tiktok.com/embed/v2/7600738854332665109",
        description:
            "Fast-paced vertical edit specifically designed for TikTok's visual language.",
    },
    {
        id: 15,
        title: "Threads: Storytelling",
        client: "@1ndian2wins",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "images/works/thumb_hq_15.jpg",
        videoUrl: "https://www.threads.net/@1ndian2wins/post/DUCiAXOAWxT/embed",
        description:
            "Engaging and raw storytelling produced for the Threads platform.",
    },
    {
        id: 16,
        title: "Instagram: Cinematic Reel",
        client: "@1ndian2wins",
        category: "FASHION",
        orientation: "portrait",
        thumbnail: "images/works/thumb_hq_16.jpg",
        videoUrl: "https://www.instagram.com/reel/DTfRhxVE6f9/embed",
        description:
            "A premium cinematic expression exploring style through Instagram Reels.",
    },
    {
        id: 17,
        title: "Maison de Onu: Party Pool",
        client: "Maison de Onu",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "images/works/thumb_hq_17.jpg",
        videoUrl: "https://www.instagram.com/reel/DTU3zQAkV14/embed",
        description:
            "광주 프리미엄 풀빌라 '메종드오누'. 청결하고 프라이빗한 파티풀 시설의 매력을 담은 감성 영상입니다.",
    },
    {
        id: 18,
        title: "Obang Heater: Originality",
        client: "오방난로",
        category: "BRAND",
        orientation: "portrait",
        thumbnail: "images/works/thumb_hq_18.jpg",
        videoUrl: "https://www.instagram.com/reel/DRwggvgk791/embed",
        description:
            "기술력에 대한 브랜드의 자신감. 세계 최초 상단 하이라이트 가열 구조를 가진 오방난로의 오리지널리티를 강조합니다.",
    },
];

export default works;
